
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2 --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 50 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/









python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-medium --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 32 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/








python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-large --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 16 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/






python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length18_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length141_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type gpt2 --model_name_or_path gpt2-xl --length 1300 --window_size 256 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 5 --pretokenized --prompt_file webtext_prompts_length564_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/


