
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length0_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length16_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length128_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 10 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 40 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 800 --p 1 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.75 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.9 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 0.95 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.0 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.7 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 0.9 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.1 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/
python generate.py --model_type transfo-xl --model_name_or_path transfo-xl-wt103 --length 1010 --window_size 1030 --temperature 1.3 --k 1234567890 --p 1.0 --beam_size 1 --batch_size 4 --prompt_file wikitext_prompts_length512_1of1.txt --output_directory ../data/prompts_and_generations/ --input_directory ../data/prompts_and_generations/

