python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_1_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_10_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_40_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_800_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_0.75_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_0.9_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_0.95_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_1.0_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_None_temp_0.7_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_None_temp_0.9_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_None_temp_1.1_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length512_1of1.txt_topk_None_topp_None_temp_1.3_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_1_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_10_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_40_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_800_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_0.75_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_0.9_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_0.95_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_1.0_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_None_temp_0.7_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_None_temp_0.9_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_None_temp_1.1_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length128_1of1.txt_topk_None_topp_None_temp_1.3_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_1_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_10_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_40_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_800_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_0.75_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_0.9_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_0.95_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_1.0_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_None_temp_0.7_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_None_temp_0.9_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_None_temp_1.1_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length16_1of1.txt_topk_None_topp_None_temp_1.3_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_1_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_10_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_40_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_800_topp_None_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_0.75_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_0.9_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_0.95_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_1.0_temp_1.0_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_None_temp_0.7_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_None_temp_0.9_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_None_temp_1.1_length_1010.generated --length 1000
python trim.py --file ../data/prompts_and_generations/lstm_wikitext_prompts_length0_1of1.txt_topk_None_topp_None_temp_1.3_length_1010.generated --length 1000
