python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.k1_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.k10_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.k40_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.k800_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_p0.75_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_p0.9_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_p0.95_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_p1.0_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_pNone_temp0.7.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_pNone_temp0.9.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_pNone_temp1.1.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length512_1of1.txt.kNone_pNone_temp1.3.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.k1_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.k10_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.k40_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.k800_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_p0.75_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_p0.9_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_p0.95_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_p1.0_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_pNone_temp0.7.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_pNone_temp0.9.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_pNone_temp1.1.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length128_1of1.txt.kNone_pNone_temp1.3.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.k1_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.k10_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.k40_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.k800_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_p0.75_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_p0.9_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_p0.95_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_p1.0_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_pNone_temp0.7.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_pNone_temp0.9.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_pNone_temp1.1.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length16_1of1.txt.kNone_pNone_temp1.3.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.k1_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.k10_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.k40_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.k800_pNone_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_p0.75_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_p0.9_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_p0.95_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_p1.0_tempNone.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_pNone_temp0.7.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_pNone_temp0.9.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_pNone_temp1.1.generated.trimmed.detokenized.sentences
python parse.py --file_to_parse ../data/prompts_and_generations/transformer_wikitext_prompts_length0_1of1.txt.kNone_pNone_temp1.3.generated.trimmed.detokenized.sentences
