python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.1.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.2.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.3.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.4.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.5.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.6.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.7.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.8.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.9.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.10.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.11.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.12.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.13.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.14.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.15.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.16.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.17.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.18.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.19.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.20.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.21.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.22.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.23.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.24.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.25.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.26.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.27.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.28.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.29.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.30.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.31.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.32.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.33.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.34.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.35.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.36.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.37.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.38.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.39.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.40.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.41.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.42.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.43.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.44.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.45.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.46.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.47.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.48.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.49.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.50.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.51.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.52.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.53.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.54.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.55.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.56.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.57.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.58.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.59.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.60.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.61.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.62.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.63.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.64.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.65.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.66.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.67.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.68.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.69.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.70.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.71.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.72.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.73.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.74.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.75.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.76.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.77.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.78.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.79.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.80.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.81.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.82.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.83.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.84.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.85.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.86.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.87.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.88.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.89.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.90.sentences --training
python parse.py --file_to_parse ../data/wikitext-103/wiki.train.tokens.detokenized.91.sentences --training
